language: go

go:
  - master

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - gox -osarch="linux/amd64 darwin/amd64 windows/amd64"
    -ldflags "-X main.Rev=`git rev-parse --short HEAD`"
    -verbose

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: L5KaouTep+MdwKubi9VLUNoprhgxe9oq118AcveldPgV43CNG9TEoU9kc/F+T+lf1hkZ3aiqzGmRR4w2Pyz+1bpfp/gj/3h6mxpQT3gs5QpQAP4TptAGhhK2WrmagDXel1H4/l0q/S6kblgVPq0zzNUZPp6/ujwT6iMFxsvopuOgiTFN7eTasS6GpOVURs5VqYeOnmilja97Q7F4PBNrP1j1sU4M8tF7BIyV4ak6QHRlbRpxoG8+KkuViRu/iVIJ0JK95QhjeXpgd+79huBxqpRaxacHwXLv3a6zZNS8MGBHx/xMttrzS9OdVtt5sWfmshgXJJYw37JC4T9n7iRL+AL6gh3tW7z8brSVhBg22K5UQnVxMkfsPglkNjXEckSGdaWKZvP2cGPZ4W5/BbsFO9JUjTB+2+IUCRcSvOx7iPoQMX28axbyrTCVcX8DR3PhyYcpSmLkzXAQaVqE808z2II0NS68bqSA+bRW5lvDRG9TJ7CgB8VhDnqOlrXF2zHZDT57PS0BKXov68XUJ0wrcPDnKpXvQj2tIWoJpgmBPOLo4otzHGFct/gbf/RDtaHW+kVfPwhkwvPGwgPaqHnpRTMUO8l87N5dsaWzxPZmNQbVpttc4iqhgQ70UIEhKDuk5JwVahMd7m57QUHfN8Tq3DbzopPcLVjGZNg437Y4kWs=
  file:
    - gosurf_windows_amd64.exe
    - gosurf_darwin_amd64
    - gosurf_linux_amd64
  on:
    repo: mhelmetag/gosurf
    tags: true
