language: go

go:
  - master

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - gox -osarch="linux/amd64 darwin/amd64 windows/amd64"
    -ldflags "-X main.Rev=`git rev-parse --short HEAD`"
    -verbose

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: oY0m/ET1vq1uWBGhtdZkYO/6Pd+81XSe6wxAT+zFOsMrHssFzHRtZKf/iCjP2LNwzl3ftuVxpo8hSQ7M2RXcUKxkZv8wWkoVubJkMprysw1xIvaB5xXD3oHnVAHWCDC+PMnBWYVUNsGQPqcVHEWxUgYlX3dkDUeDVHnjcrJpMjK+2X5guuz1ixIu9+F3PmCQe5bI71S5usN1B8xjAoUmb4eo13/bKJJcx8SSa2zowdlYPOQVHaV1oCfq71GumyWt4DoAmiBoqlmEBaHHwG6mwXTbMScjxhZRlCMpXoGOYlvWUnOWY5Be7adugz4JuCvYuM0d0zQstyfATqinkOnyHzKKesgD14EsRIYVZEU1Q+9wmR6gkKJ7WnX/mzHuF0+eXfzkHtXbIHRCtrV21oWvmL0N6sUl3cN6F62grr1cIFC7+GRihwHjdM0l8MI5YB3FBKj8Ox4KdKLDk9/xPGBqspo+/k+RVT1EItcFzFE84PJrNbtwc85N1iZiJJOlViSuCqPACmrXrM6ahEDxZczZY0w2UQLR7PtLkwVSmAvVrIISC5bohh/GeVMTNLqo7MR9IlRdm63ATx633cJd92FLTbvUbV8nQXdnOHZ0CJVS61AjWaUvFCMvRqWYJNsfwS01g4YSNmduPHrlzJUkqso5HgJv7rL9TB7tkj+TfRhQiIs=
  file:
    - gosurf_windows_amd64.exe
    - gosurf_darwin_amd64
    - gosurf_linux_amd64
  on:
    repo: mhelmetag/gosurf
    tags: true
