name: Publish

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-test"

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Install gox
        run: go install github.com/mitchellh/gox@v1.0.1

      - name: Compile binaries with gox
        run: ${{ env.GOPATH }}/bin/gox -osarch="linux/amd64 linux/arm darwin/amd64 darwin/arm windows/amd64" -ldflags "-X main.Rev=`git rev-parse --short HEAD`"  -verbose

      - name: Publish release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gosurf_linux_amd64
            gosurf_linux_arm
            gosurf_darwin_amd64
            gosurf_darwin_arm
            gosurf_windows_amd64.exe
